<?php

include_once 'helper.php';
//
$variables = array(
    'name' => 'primary_items',
    'state' => 'default'
);
$primary_default = get_include_contents('ajax.panel.item.view.phtml', $variables);
//
$variables = array(
    'name' => 'primary_items',
    'state' => 'hover'
);
$primary_hover = get_include_contents('ajax.panel.item.view.phtml', $variables);
//
$variables = array(
    'name' => 'primary_items',
    'state' => 'active'
);
$primary_active = get_include_contents('ajax.panel.item.view.phtml', $variables);
//
$variables = array(
    'name' => 'secondary_items',
    'state' => 'default'
);
$secondary_default = get_include_contents('ajax.panel.item.view.phtml', $variables);
//
$variables = array(
    'name' => 'secondary_items',
    'state' => 'hover'
);
$secondary_hover = get_include_contents('ajax.panel.item.view.phtml', $variables);
//
$variables = array(
    'name' => 'secondary_items',
    'state' => 'active'
);
$secondary_active = get_include_contents('ajax.panel.item.view.phtml', $variables);

?>

<div class="app__menu-constructor" data-element="App.MenuConstructor" data-node="AppMenuConstructor:{}:container">
    <div class="app__panel__box">
        <dl class="pt__field is-box">
            <dt>Name</dt>
            <dd>
                <input type="text" name="title">
            </dd>
        </dl>
    </div>
    <dl class="com__togglebox app__panel__togglebox is-ui has-title-bg is-show" data-element="Com.ToggleBox" data-config='{"remember" : true, "name" : "form__menu-designer__primary-menu-items"}' data-node="ComToggleBox.container">
        <dt data-node="ComToggleBox.button">
            <span class="icon default"></span>
            <span class="title">Primary Menu Items</span>
        </dt>
        <dd data-node="ComToggleBox.target">
            <div class="app__panel__box">
                <dl class="pt__field is-box">
                    <dt>
                        Click to edit styles
                        <span class="com__help-bubble" data-element="Com.HelpBubble" data-node="ComHelpBubble:{}:container">
                            <span class="icon default linked" data-node="button"></span>
                            <span class="com__help-bubble__content" data-node="content">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</span>
                        </span>
                    </dt>
                    <dd>
                        <div class="pt__buttons pull-justify">
                            <div class="inner">
                                <div class="cm__button-wrapper" data-element="App.PanelContainer" data-node="AppPanelContainer:{}:container" data-config='{"title" : "Default State"}'>
                                    <div class="button button-secondary" data-node="button">Default</div>
                                    <div class="hidden" data-node="holder">
                                        <div data-node="content">
                                            <?=$primary_default?>
                                        </div>
                                    </div>
                                </div>
                                <div class="cm__button-wrapper" data-element="App.PanelContainer" data-node="AppPanelContainer:{}:container" data-config='{"title" : "Hover State"}'>
                                    <div class="button button-middle" data-node="button">Hover</div>
                                    <div class="hidden" data-node="holder">
                                        <div data-node="content">
                                            <?=$primary_hover?>
                                        </div>
                                    </div>
                                </div>
                                <div class="cm__button-wrapper" data-element="App.PanelContainer" data-node="AppPanelContainer:{}:container" data-config='{"title" : "Active State"}'>
                                    <div class="button button-primary" data-node="button">Active</div>
                                    <div class="hidden" data-node="holder">
                                        <div data-node="content">
                                            <?=$primary_active?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </dd>
                </dl>
                <div class="pt__columns">
                    <div class="inner">
                        <div class="column">
                            <dl class="pt__field is-box align-center">
                                <dt>Item Inner Padding</dt>
                                <dd>
                                    <input type="text" value="0" data-element="Com.BoxTools" name="params[primary_items][inner-padding]">
                                </dd>
                            </dl>
                        </div>
                        <div class="column">
                            <dl class="pt__field is-box align-center">
                                <dt>Indent Between Items</dt>
                                <dd>
                                    <input type="number" min="0" max="999" value="0" data-element="Com.IndentInput" name="params[primary_items][inner-between]" data-config='{"allowNegative" : true}'>
                                </dd>
                            </dl>
                        </div>
                    </div>
                </div>
            </div>
        </dd>
    </dl>
    <dl class="com__togglebox app__panel__togglebox is-ui has-title-bg is-show" data-element="Com.ToggleBox" data-config='{"remember" : true, "name" : "form__menu-designer__secondary-menu-items"}' data-node="ComToggleBox.container">
        <dt data-node="ComToggleBox.button">
            <span class="icon default"></span>
            <span class="title">Secondary Menu Items</span>
        </dt>
        <dd data-node="ComToggleBox.target">
            <div class="app__panel__box">
                <dl class="pt__field is-box">
                    <dt>
                        Click to edit styles
                        <span class="com__help-bubble" data-element="Com.HelpBubble" data-node="ComHelpBubble:{}:container">
                            <span class="icon default linked" data-node="button"></span>
                            <span class="com__help-bubble__content" data-node="content">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</span>
                        </span>
                    </dt>
                    <dd>
                        <div class="pt__buttons pull-justify">
                            <div class="inner">
                                <div class="cm__button-wrapper" data-element="App.PanelContainer" data-node="AppPanelContainer:{}:container" data-config='{"title" : "Default State"}'>
                                    <div class="button button-secondary" data-node="button">Default</div>
                                    <div class="hidden" data-node="holder">
                                        <div data-node="content">
                                            <?=$secondary_default?>
                                        </div>
                                    </div>
                                </div>
                                <div class="cm__button-wrapper" data-element="App.PanelContainer" data-node="AppPanelContainer:{}:container" data-config='{"title" : "Hover State"}'>
                                    <div class="button button-middle" data-node="button">Hover</div>
                                    <div class="hidden" data-node="holder">
                                        <div data-node="content">
                                            <?=$secondary_hover?>
                                        </div>
                                    </div>
                                </div>
                                <div class="cm__button-wrapper" data-element="App.PanelContainer" data-node="AppPanelContainer:{}:container" data-config='{"title" : "Active State"}'>
                                    <div class="button button-primary" data-node="button">Active</div>
                                    <div class="hidden" data-node="holder">
                                        <div data-node="content">
                                            <?=$secondary_active?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </dd>
                </dl>
                <div class="pt__columns">
                    <div class="inner">
                        <div class="column">
                            <dl class="pt__field is-box align-center">
                                <dt>Item Inner Padding</dt>
                                <dd>
                                    <input type="text" value="0" data-element="Com.BoxTools" name="params[secondary_items][inner-padding]">
                                </dd>
                            </dl>
                        </div>
                        <div class="column">
                            <dl class="pt__field is-box align-center">
                                <dt>Indent Between Items</dt>
                                <dd>
                                    <input type="number" min="0" max="999" value="0" data-element="Com.IndentInput" name="params[secondary_items][inner-between]" data-config='{"allowNegative" : true}'>
                                </dd>
                            </dl>
                        </div>
                    </div>
                </div>
            </div>
        </dd>
    </dl>
    <dl class="com__togglebox app__panel__togglebox is-ui has-title-bg is-hide" data-element="Com.ToggleBox" data-config='{"remember" : true, "name" : "form__menu-designer__primary-menu-container"}' data-node="ComToggleBox.container">
        <dt data-node="ComToggleBox.button">
            <span class="icon default"></span>
            <span class="title">Primary Menu Container</span>
        </dt>
        <dd data-node="ComToggleBox.target">
            <div class="app__panel__box">
                <dl class="pt__field is-box">
                    <dt>Background Color</dt>
                    <dd>
                        <input type="text" data-element="Com.ColorPicker" data-config='{"size" : "full"}' name="params[primary_container][background-color]">
                    </dd>
                </dl>
                <dl class="pt__field is-box">
                    <dt>Background Image</dt>
                    <dd>
                        <input type="text" data-element="App.ImageInput" data-config='{"size" : "full"}' name="params[primary_container][background-image]">
                    </dd>
                </dl>
                <div class="pt__columns is-space-between">
                    <div class="inner">
                        <div class="column">
                            <dl class="pt__field is-box field-indent">
                                <dt>Repeat</dt>
                                <dd>
                                    <input type="text" data-element="Com.RepeatTools" name="params[primary_container][background-repeat]">
                                </dd>
                            </dl>
                            <dl class="pt__field is-box field-indent">
                                <dt>Scaling</dt>
                                <dd>
                                    <input type="text" data-element="Com.ScaleTools" name="params[primary_container][background-scaling]">
                                </dd>
                            </dl>
                        </div>
                        <div class="column">
                            <dl class="pt__field is-box field-indent">
                                <dt>Position</dt>
                                <dd>
                                    <input type="text" data-element="Com.PositionTools" name="params[primary_container][background-position]">
                                </dd>
                            </dl>
                            <dl class="pt__field is-box field-indent">
                                <dd>
                                    <div class="check-line">
                                        <input type="checkbox" name="params[primary_container][background-attachment]">
                                        <label for="params[primary_container][background-attachment]">Parallax</label>
                                    </div>
                                </dd>
                            </dl>
                        </div>
                    </div>
                </div>
                <hr>
                <div class="pt__columns">
                    <div class="inner">
                        <div class="column">
                            <dl class="pt__field is-box align-center">
                                <dt>Border Size</dt>
                                <dd>
                                    <input type="text" value="0" data-element="Com.BoxTools" name="params[primary_container][border-size]">
                                </dd>
                            </dl>
                            <dl class="pt__field is-box align-center">
                                <dt>Border Style</dt>
                                <dd>
                                    <select data-element="Com.Select" name="params[primary_container][border-style]">
                                        <option value="solid">Solid</option>
                                        <option value="dotted">Dotted</option>
                                        <option value="dashed">Dashed</option>
                                        <option value="double">Double</option>
                                        <option value="groove">Groove</option>
                                        <option value="ridge">Ridge</option>
                                        <option value="inset">Inset</option>
                                        <option value="outset">Outset</option>
                                    </select>
                                </dd>
                            </dl>
                        </div>
                        <div class="column">
                            <dl class="pt__field is-box align-center">
                                <dt>Border Radius</dt>
                                <dd>
                                    <input type="text" value="0" data-element="Com.BoxRadiusTools" name="params[primary_container][border-radius]">
                                </dd>
                            </dl>
                            <dl class="pt__field is-box align-center">
                                <dt>Border Color</dt>
                                <dd>
                                    <input type="text" data-element="Com.ColorPicker" name="params[primary_container][border-color]">
                                </dd>
                            </dl>
                        </div>
                    </div>
                </div>
                <hr>
                <div class="pt__columns">
                    <div class="inner">
                        <div class="column">
                            <dl class="pt__field is-box align-center">
                                <dt>Inner Padding</dt>
                                <dd>
                                    <input type="text" value="0" data-element="Com.BoxTools" name="params[primary_container][inner-padding]">
                                </dd>
                            </dl>
                        </div>
                        <div class="column">
                        </div>
                    </div>
                </div>
            </div>
        </dd>
    </dl>
    <dl class="com__togglebox app__panel__togglebox is-ui has-title-bg is-hide" data-element="Com.ToggleBox" data-config='{"remember" : true, "name" : "form__menu-designer__secondary-menu-container"}' data-node="ComToggleBox.container">
        <dt data-node="ComToggleBox.button">
            <span class="icon default"></span>
            <span class="title">Secondary Menu Container</span>
        </dt>
        <dd data-node="ComToggleBox.target">
            <div class="app__panel__box">
                <dl class="pt__field is-box">
                    <dt>Background Color</dt>
                    <dd>
                        <input type="text" data-element="Com.ColorPicker" data-config='{"size" : "full"}' name="params[secondary_container][background-color]">
                    </dd>
                </dl>
                <dl class="pt__field is-box">
                    <dt>Background Image</dt>
                    <dd>
                        <input type="text" data-element="App.ImageInput" data-config='{"size" : "full"}' name="params[secondary_container][background-image]">
                    </dd>
                </dl>
                <div class="pt__columns is-space-between">
                    <div class="inner">
                        <div class="column">
                            <dl class="pt__field is-box field-indent">
                                <dt>Repeat</dt>
                                <dd>
                                    <input type="text" data-element="Com.RepeatTools" name="params[secondary_container][background-repeat]">
                                </dd>
                            </dl>
                            <dl class="pt__field is-box field-indent">
                                <dt>Scaling</dt>
                                <dd>
                                    <input type="text" data-element="Com.ScaleTools" name="params[secondary_container][background-scaling]">
                                </dd>
                            </dl>
                        </div>
                        <div class="column">
                            <dl class="pt__field is-box field-indent">
                                <dt>Position</dt>
                                <dd>
                                    <input type="text" data-element="Com.PositionTools" name="params[secondary_container][background-position]">
                                </dd>
                            </dl>
                            <dl class="pt__field is-box field-indent">
                                <dd>
                                    <div class="check-line">
                                        <input type="checkbox" name="params[secondary_container][background-attachment]">
                                        <label for="params[secondary_container][background-attachment]">Parallax</label>
                                    </div>
                                </dd>
                            </dl>
                        </div>
                    </div>
                </div>
                <hr>
                <div class="pt__columns">
                    <div class="inner">
                        <div class="column">
                            <dl class="pt__field is-box align-center">
                                <dt>Border Size</dt>
                                <dd>
                                    <input type="text" value="0" data-element="Com.BoxTools" name="params[secondary_container][border-size]">
                                </dd>
                            </dl>
                            <dl class="pt__field is-box align-center">
                                <dt>Border Style</dt>
                                <dd>
                                    <select data-element="Com.Select" name="params[secondary_container][border-style]">
                                        <option value="solid">Solid</option>
                                        <option value="dotted">Dotted</option>
                                        <option value="dashed">Dashed</option>
                                        <option value="double">Double</option>
                                        <option value="groove">Groove</option>
                                        <option value="ridge">Ridge</option>
                                        <option value="inset">Inset</option>
                                        <option value="outset">Outset</option>
                                    </select>
                                </dd>
                            </dl>
                        </div>
                        <div class="column">
                            <dl class="pt__field is-box align-center">
                                <dt>Border Radius</dt>
                                <dd>
                                    <input type="text" value="0" data-element="Com.BoxRadiusTools" name="params[secondary_container][border-radius]">
                                </dd>
                            </dl>
                            <dl class="pt__field is-box align-center">
                                <dt>Border Color</dt>
                                <dd>
                                    <input type="text" data-element="Com.ColorPicker" name="params[secondary_container][border-color]">
                                </dd>
                            </dl>
                        </div>
                    </div>
                </div>
                <hr>
                <div class="pt__columns">
                    <div class="inner">
                        <div class="column">
                            <dl class="pt__field is-box align-center">
                                <dt>Inner Padding</dt>
                                <dd>
                                    <input type="text" value="0" data-element="Com.BoxTools" name="params[secondary_container][inner-padding]">
                                </dd>
                            </dl>
                        </div>
                        <div class="column">
                        </div>
                    </div>
                </div>
            </div>
        </dd>
    </dl>
    <dl class="com__togglebox app__panel__togglebox is-ui has-title-bg is-hide" data-element="Com.ToggleBox" data-config='{"remember" : true, "name" : "form__menu-designer__mobile-view"}' data-node="ComToggleBox.container">
        <dt data-node="ComToggleBox.button">
            <span class="icon default"></span>
            <span class="title">Mobile View</span>
        </dt>
        <dd data-node="ComToggleBox.target">
            <div class="app__panel__box">
                <dl class="pt__field is-box">
                    <dt>
                        Click to edit font properties
                        <span class="com__help-bubble" data-element="Com.HelpBubble" data-node="ComHelpBubble:{}:container">
                            <span class="icon default linked" data-node="button"></span>
                            <span class="com__help-bubble__content" data-node="content">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</span>
                        </span>
                    </dt>
                    <dd>
                        <input type="text" placeholder="The quick brown fox jumps over the lazy dog" data-element="App.FontInput" data-config='{"name" : "params[mobile][font]", "showResetButtons" : false, "defaultValue" : {"font-family":"Open Sans, sans-serif","line-height":"20px","font-size":"14px","font-weight":"400","color":"#666666","text-decoration":"none","font-style":"normal"}}'>
                    </dd>
                </dl>
                <hr>
                <dl class="pt__field is-box">
                    <dt>Background Color</dt>
                    <dd>
                        <input type="text" data-element="Com.ColorPicker" data-config='{"size" : "full"}' name="params[mobile][background-color]">
                    </dd>
                </dl>
                <dl class="pt__field is-box">
                    <dt>Menu Icon</dt>
                    <dd>
                        <input type="text" data-element="Com.ImageInput" data-config='{"size" : "full"}' name="params[mobile][menu-icon]">
                    </dd>
                </dl>
                <hr>
                <div class="pt__columns">
                    <div class="inner">
                        <div class="column">
                            <dl class="pt__field is-box align-center">
                                <dt>Border Size</dt>
                                <dd>
                                    <input type="text" value="0" data-element="Com.BoxTools" name="params[mobile][border-size]">
                                </dd>
                            </dl>
                            <dl class="pt__field is-box align-center">
                                <dt>Border Style</dt>
                                <dd>
                                    <select data-element="Com.Select" name="params[mobile][border-style]">
                                        <option value="solid">Solid</option>
                                        <option value="dotted">Dotted</option>
                                        <option value="dashed">Dashed</option>
                                        <option value="double">Double</option>
                                        <option value="groove">Groove</option>
                                        <option value="ridge">Ridge</option>
                                        <option value="inset">Inset</option>
                                        <option value="outset">Outset</option>
                                    </select>
                                </dd>
                            </dl>
                        </div>
                        <div class="column">
                            <dl class="pt__field is-box align-center">
                                <dt>Border Radius</dt>
                                <dd>
                                    <input type="text" value="0" data-element="Com.BoxRadiusTools" name="params[mobile][border-radius]">
                                </dd>
                            </dl>
                            <dl class="pt__field is-box align-center">
                                <dt>Border Color</dt>
                                <dd>
                                    <input type="text" data-element="Com.ColorPicker" name="params[mobile][border-color]">
                                </dd>
                            </dl>
                        </div>
                    </div>
                </div>
                <hr>
                <div class="pt__columns">
                    <div class="inner">
                        <div class="column">
                            <dl class="pt__field is-box align-center">
                                <dt>Inner Padding</dt>
                                <dd>
                                    <input type="text" value="0" data-element="Com.BoxTools" name="params[mobile][inner-padding]">
                                </dd>
                            </dl>
                        </div>
                        <div class="column"></div>
                    </div>
                </div>
            </div>
        </dd>
    </dl>
</div>