<div class="app__module app-mod__element" data-element="Mod.ElementTextArea" data-node="ModElementTextArea:{}:container" data-config='{"required" : true}'>
    <dl data-node="field">
        <dt><label for="element_textarea">Input Text:</label></dt>
        <dd>
            <textarea name="element_textarea" data-node="input"></textarea>
            <ul class="hint hidden" data-node="errors">
                <li>Value is required and can't be empty</li>
            </ul>
        </dd>
    </dl>
</div>