<div class="app__module app-mod__element" data-element="Mod.ElementPassword" data-node="ModElementPassword:{}:container" data-config='{"required" : true, "name" : "password"}'>
    <dl data-node="field">
        <dt><label for="element_password">Password Text:</label></dt>
        <dd>
            <input name="element_password" type="password" data-node="input">
            <ul class="hint hidden" data-node="errors">
                <li>Value is required and can't be empty</li>
            </ul>
        </dd>
    </dl>
</div>