<div class="app__module app-mod__element" data-element="Mod.ElementCheckbox" data-node="ModElementCheckbox:{}:container" data-config='{"required" : true, "name" : "element_checkbox"}'>
    <dl data-node="field">
        <dt><label for="element_checkbox">Checkbox:</label></dt>
        <dd>
            <input name="element_checkbox" type="checkbox" data-node="input" required>
            <ul class="hint hidden" data-node="errors">
                <li>Value is required and can't be empty</li>
            </ul>
        </dd>
    </dl>
</div>