<div class="app__module app-mod__element" data-element="Mod.ElementMultiCheckbox" data-node="ModElementMultiCheckbox:{}:container" data-config='{"required" : true}'>
    <dl data-node="field">
        <dt><label for="element_multicheckbox">Multi Checkbox:</label></dt>
        <dd>
            <div class="check-line">
                <input name="element_multicheckbox[]" type="checkbox" value="1" data-node="inputs:[]:input">
                <label>Option 1</label>
            </div>
            <div class="check-line">
                <input name="element_multicheckbox[]" type="checkbox" value="2" data-node="inputs:[]:input">
                <label>Option 2</label>
            </div>
            <div class="check-line">
                <input name="element_multicheckbox[]" type="checkbox" value="3" data-node="inputs:[]:input">
                <label>Option 3</label>
            </div>
            <ul class="hint hidden" data-node="errors">
                <li>Value is required and can't be empty</li>
            </ul>
        </dd>
    </dl>
</div>