<div class="app__module app-mod__element" data-element="Mod.ElementFileUploader" data-node="ModElementFileUploader:{}:container" data-config='{"required" : true, "name" : "element_fileuploader"}'>
    <dl data-node="field">
        <dt><label for="element_fileuploader">Input Text:</label></dt>
        <dd>
            <input type="text" data-element="App.FileInput" name="element_fileuploader">
            <ul class="hint hidden" data-node="errors">
                <li>Value is required and can't be empty</li>
            </ul>
        </dd>
    </dl>
</div>